// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvdokruyvhcnqodrnkqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2ZG9rcnV5dmhjbnFvZHJua3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODg3MjMsImV4cCI6MjA3MDY2NDcyM30.ZF4uhW1nA6zaWMB2NqjpKEpAfT2y_Lo1SO1MZNGjV9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});